/*
 * xHarbour build 1.1.0 Intl. (SimpLex)
 * Generated C source code from <FUNCS.PRG>
 * Command: C:\Xharbour\bin\harbour.exe C:\GEFYRES\PRG\FUNCS.PRG /n /es2 /gc1 /oC:\GEFYRES\PRG\FUNCS /iC:\FWH\INCLUDE /iC:\xHarbour\include /iC:\FWH\include;C:\GEFYRES\PRG /iC:\Xharbour\include 
 * Created: 2021.07.29 19:24:13 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "FUNCS.PRG"

HB_FUNC( PADL );
HB_FUNC( PADR );
HB_FUNC( RPAD );
HB_FUNC_EXTERN( RIGHT );
HB_FUNC_EXTERN( REPLICATE );
HB_FUNC_EXTERN( PCOUNT );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( TRANSFORM );
HB_FUNC_EXTERN( LEFT );
HB_FUNC_EXTERN( GETPROCADDRESS );
HB_FUNC_EXTERN( TACTIVEX );
HB_FUNC_EXTERN( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 9

#include "hbapi.h"


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_FUNCS )
{ "PADL", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( PADL )}, NULL },
{ "LEXP", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LNO", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "LPAD", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "RIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( RIGHT )}, NULL },
{ "REPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( REPLICATE )}, NULL },
{ "PCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PCOUNT )}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "TRANSFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSFORM )}, NULL },
{ "PADR", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( PADR )}, NULL },
{ "LEFT", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEFT )}, NULL },
{ "RPAD", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( RPAD )}, NULL },
{ "GETPROCADDRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETPROCADDRESS )}, NULL },
{ "TACTIVEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( TACTIVEX )}, NULL },
{ "ERRORSYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERRORSYS )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_FUNCS )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_FUNCS
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_FUNCS = hb_vm_SymbolInit_FUNCS;
   #pragma data_seg()
#endif

HB_FUNC( PADL )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 3,
	HB_P_PARAMETER, 1, 0, 1,
	HB_P_PARAMETER, 2, 0, 2,
	HB_P_PARAMETER, 3, 0, 3,
	HB_P_BASELINE, 38, 0,
	HB_P_PUSHSYMNEAR, 4,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 5,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 6,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 3,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 7,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_JUMPNEAR, 6,
	HB_P_PUSHSTRSHORT, 2,
	' ', 0, 
	HB_P_PUSHVARIABLE, 2, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSYMNEAR, 7,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 8,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,
	HB_P_PUSHSTRSHORT, 1,
	0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 2, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_RETVALUE,
	HB_P_ENDPROC
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( PADR )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 3,
	HB_P_PARAMETER, 1, 0, 1,
	HB_P_PARAMETER, 2, 0, 2,
	HB_P_PARAMETER, 3, 0, 3,
	HB_P_BASELINE, 43, 0,
	HB_P_PUSHSYMNEAR, 10,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 7,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 8,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,
	HB_P_PUSHSTRSHORT, 1,
	0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 5,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 6,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 3,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 7,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_JUMPNEAR, 6,
	HB_P_PUSHSTRSHORT, 2,
	' ', 0, 
	HB_P_PUSHVARIABLE, 2, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 2, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_RETVALUE,
	HB_P_ENDPROC
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( RPAD )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 3,
	HB_P_PARAMETER, 1, 0, 1,
	HB_P_PARAMETER, 2, 0, 2,
	HB_P_PARAMETER, 3, 0, 3,
	HB_P_BASELINE, 48, 0,
	HB_P_PUSHSYMNEAR, 10,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 7,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 8,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 1, 0,
	HB_P_PUSHSTRSHORT, 1,
	0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSYMNEAR, 5,
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 6,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 3,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 7,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_JUMPNEAR, 6,
	HB_P_PUSHSTRSHORT, 2,
	' ', 0, 
	HB_P_PUSHVARIABLE, 2, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHVARIABLE, 2, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_RETVALUE,
	HB_P_ENDPROC
   };

   hb_vmExecute( pcode, symbols );
}

