/*
 * xHarbour build 1.1.0 Intl. (SimpLex)
 * Generated C source code from <THLKAT.PRG>
 * Command: C:\Xharbour\bin\harbour.exe C:\GEFYRES\PRG\THLKAT.PRG /n /es2 /gc1 /oC:\GEFYRES\PRG\THLKAT /iC:\FWH\INCLUDE /iC:\xHarbour\include /iC:\FWH\include;C:\GEFYRES\PRG /iC:\Xharbour\include 
 * Created: 2021.08.02 15:34:25 (Borland C++ 5.5.1)
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "THLKAT.PRG"

HB_FUNC( THLKAT );
HB_FUNC( KATALOGOS );
HB_FUNC_EXTERN( SET );
HB_FUNC_EXTERN( __SETCENTURY );
HB_FUNC_EXTERN( TFONT );
HB_FUNC_EXTERN( GETSYSTEMFONT );
HB_FUNC_EXTERN( TDIALOG );
HB_FUNC_EXTERN( GETPROCADDRESS );
HB_FUNC_EXTERN( TACTIVEX );
HB_FUNC_EXTERN( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 9

#include "hbapi.h"


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_THLKAT )
{ "THLKAT", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( THLKAT )}, NULL },
{ "SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SET )}, NULL },
{ "__SETCENTURY", {HB_FS_PUBLIC}, {HB_FUNCNAME( __SETCENTURY )}, NULL },
{ "NACOLOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NBCOLOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "NEW", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "TFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TFONT )}, NULL },
{ "GETSYSTEMFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETSYSTEMFONT )}, NULL },
{ "OFONT", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "TDIALOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( TDIALOG )}, NULL },
{ "ACTIVATE", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BLCLICKED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BMOVED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BPAINTED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "SETCOLOR", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "BRCLICKED", {HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE}, {NULL}, NULL },
{ "KATALOGOS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( KATALOGOS )}, NULL },
{ "GETPROCADDRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETPROCADDRESS )}, NULL },
{ "TACTIVEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( TACTIVEX )}, NULL },
{ "ERRORSYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERRORSYS )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_THLKAT )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_THLKAT
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_THLKAT = hb_vm_SymbolInit_THLKAT;
   #pragma data_seg()
#endif

HB_FUNC( THLKAT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 8, 0,
	HB_P_BASELINE, 33, 0,
	HB_P_PUSHSYMNEAR, 1,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,
	HB_P_PUSHSYMNEAR, 2,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 17,
	HB_P_PUSHSTRSHORT, 11,
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 'y', 'y', 0, 
	HB_P_JUMPNEAR, 13,
	HB_P_PUSHSTRSHORT, 9,
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 0, 
	HB_P_DOSHORT, 2,
	HB_P_LINEOFFSET, 1,
	HB_P_PUSHSYMNEAR, 1,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,
	HB_P_PUSHINT, 198, 7,
	HB_P_DOSHORT, 2,
	HB_P_LINEOFFSET, 2,
	HB_P_PUSHSYMNEAR, 1,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,
	HB_P_PUSHSTRSHORT, 11,
	'D', 'D', '/', 'M', 'M', '/', 'Y', 'Y', 'Y', 'Y', 0, 
	HB_P_DOSHORT, 2,
	HB_P_LINEOFFSET, 4,
	HB_P_PUSHLONG, 205, 205, 193, 0, 
	HB_P_POPVARIABLE, 3, 0,
	HB_P_LINEOFFSET, 5,
	HB_P_PUSHLONG, 228, 230, 231, 0, 
	HB_P_POPVARIABLE, 4, 0,
	HB_P_LINEOFFSET, 8,
	HB_P_MESSAGE, 5, 0,
	HB_P_PUSHSYMNEAR, 6,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 7,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 244,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPVARIABLE, 8, 0,
	HB_P_LINEOFFSET, 13,
	HB_P_MESSAGE, 5, 0,
	HB_P_PUSHSYMNEAR, 9,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,
	' ', 't', 'h', 'l', 'K', 'a', 't', ' ', 0, 
	HB_P_PUSHSTRSHORT, 8,
	'p', 'e', 'l', 'a', 't', 'e', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_PUSHVARIABLE, 4, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 20,
	HB_P_POPLOCALNEAR, 2,
	HB_P_LINEOFFSET, 22,
	HB_P_MESSAGE, 10, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_MESSAGE, 11, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 12, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 13, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 23, 0,
	1, 0,
	1, 0,
	2, 0,
	HB_P_MESSAGE, 14, 0,
	HB_P_PUSHLOCALNEAR, 255,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_PUSHVARIABLE, 4, 0,
	HB_P_SENDSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 15, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
	HB_P_LINEOFFSET, 26,
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( KATALOGOS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 9, 0,
	HB_P_BASELINE, 65, 0,
	HB_P_PUSHSYMNEAR, 1,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,
	HB_P_PUSHSYMNEAR, 2,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 17,
	HB_P_PUSHSTRSHORT, 11,
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 'y', 'y', 0, 
	HB_P_JUMPNEAR, 13,
	HB_P_PUSHSTRSHORT, 9,
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 0, 
	HB_P_DOSHORT, 2,
	HB_P_LINEOFFSET, 1,
	HB_P_PUSHSYMNEAR, 1,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 5,
	HB_P_PUSHINT, 198, 7,
	HB_P_DOSHORT, 2,
	HB_P_LINEOFFSET, 2,
	HB_P_PUSHSYMNEAR, 1,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,
	HB_P_PUSHSTRSHORT, 11,
	'D', 'D', '/', 'M', 'M', '/', 'Y', 'Y', 'Y', 'Y', 0, 
	HB_P_DOSHORT, 2,
	HB_P_LINEOFFSET, 4,
	HB_P_PUSHLONG, 205, 205, 193, 0, 
	HB_P_POPVARIABLE, 3, 0,
	HB_P_LINEOFFSET, 5,
	HB_P_PUSHLONG, 228, 230, 231, 0, 
	HB_P_POPVARIABLE, 4, 0,
	HB_P_LINEOFFSET, 8,
	HB_P_MESSAGE, 5, 0,
	HB_P_PUSHSYMNEAR, 6,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSYMNEAR, 7,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 244,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPVARIABLE, 8, 0,
	HB_P_LINEOFFSET, 12,
	HB_P_MESSAGE, 5, 0,
	HB_P_PUSHSYMNEAR, 9,
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,
	' ', 't', 'h', 'l', 'K', 'a', 't', ' ', 0, 
	HB_P_PUSHSTRSHORT, 10,
	'K', 'A', 'T', 'A', 'L', 'O', 'G', 'O', 'S', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_PUSHVARIABLE, 4, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 20,
	HB_P_POPLOCALNEAR, 2,
	HB_P_LINEOFFSET, 18,
	HB_P_MESSAGE, 10, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_MESSAGE, 11, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 12, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 13, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 23, 0,
	1, 0,
	1, 0,
	2, 0,
	HB_P_MESSAGE, 14, 0,
	HB_P_PUSHLOCALNEAR, 255,
	HB_P_PUSHVARIABLE, 3, 0,
	HB_P_PUSHVARIABLE, 4, 0,
	HB_P_SENDSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 15, 0,
	HB_P_PUSHLOCALNEAR, 2,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
	HB_P_LINEOFFSET, 22,
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
   };

   hb_vmExecute( pcode, symbols );
}

